from setuptools import find_packages, setup

package_name = "visual_grasp_manu"

setup(
    name=package_name,
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    data_files=[
        ("share/ament_index/resource_index/packages", [f"resource/{package_name}"]),
        (f"share/{package_name}", ["package.xml"]),
        (
            f"share/{package_name}/config",
            [
                "config/demo_grasps.yaml",
                "config/grasp_demo.yaml",
                "config/pipeline.yaml",
                "config/camera_pose_overlay.rviz",
                "config/live_interactive_mask_mesh.rviz",
                "config/object_scan_camera_pose.rviz",
                "config/precomputed_mask_pose_demo.rviz",
                "config/pose_stub.yaml",
                "config/pose_stub_grasp_demo.rviz",
            ],
        ),
        (
            f"share/{package_name}/launch",
            [
                "launch/grasp_candidates.launch.py",
                "launch/bonn_box_camera_pose_overlay.launch.py",
                "launch/camera_pose_overlay.launch.py",
                "launch/live_interactive_mask_mesh_demo.launch.py",
                "launch/object_scan_dataset_export.launch.py",
                "launch/object_scan_camera_pose.launch.py",
                "launch/pose_stub_grasp_demo.launch.py",
                "launch/precomputed_mask_pose_demo.launch.py",
                "launch/robot_scan_dataset_record.launch.py",
                "launch/rtabmap_rgbd_slam.launch.py",
            ],
        ),
    ],
    install_requires=["setuptools"],
    zip_safe=True,
    maintainer="Project Maintainer",
    maintainer_email="maintainer@example.com",
    description="Configurable visual grasp candidate generation for ROS 2 RGB-D streams.",
    license="MIT",
    tests_require=["pytest"],
    entry_points={
        "console_scripts": [
            "grasp_candidate_node = visual_grasp_manu.grasp_candidate_node:main",
            "camera_pose_visualizer_node = visual_grasp_manu.camera_pose_visualizer_node:main",
            "bonn_scan_extract = visual_grasp_manu.bonn_scan_extract:main",
            "bonn_scan_replay_node = visual_grasp_manu.bonn_scan_replay_node:main",
            "pose_stub_node = visual_grasp_manu.pose_stub_node:main",
            "precomputed_mask_pose_demo_node = visual_grasp_manu.precomputed_mask_pose_demo_node:main",
            "prepare_rosbag2_sqlite = visual_grasp_manu.rosbag2_dataset:main",
            "generate_grounded_sam2_masks = visual_grasp_manu.mask_generation:main",
            "interactive_rosbag_mesh_demo = visual_grasp_manu.interactive_rosbag_mesh_demo:main",
            "interactive_track_masks = visual_grasp_manu.interactive_mask_tracking:main",
            "live_interactive_mask_mesh_node = visual_grasp_manu.live_interactive_mask_mesh_node:main",
            "preview_scan_masks = visual_grasp_manu.mask_preview:main",
            "generate_tsdf_mesh = visual_grasp_manu.tsdf_mesh:main",
            "visualize_mesh = visual_grasp_manu.mesh_visualization:main",
            "scan_dataset_recorder_node = visual_grasp_manu.scan_dataset_recorder_node:main",
            "validate_input = visual_grasp_manu.input_validation:main",
            "validate_scan_dataset = visual_grasp_manu.scan_dataset:main",
        ],
    },
)
